---

- name: Copy Docker EE installation script
  copy:
    src: "{{ DOCKER_EE_INSTALL_SCRIPT }}"
    dest: /home/treeptik/
    owner: treeptik
    group: treeptik
    mode: 0755

- name: Copy dockercoins stack
  copy:
    src: "{{ DOCKERCOINS_COMPOSE_FILE }}"
    dest: /home/treeptik/
    owner: treeptik
    group: treeptik
    mode: 0755
