---

- hosts: student
  strategy: free
  gather_facts: False
  remote_user: root

  roles:
    - authorized_keys
    - install_docker_yum
    - install_packages_yum
    - install_docker-compose
    - update_treeptik_user
