---

- name: Create user student
  user:
    name: student
    password: "{{ 'student' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    update_password: on_create
  become: true
