---

- name: Install Ansible
  package:
    name: ansible
    state: latest
  become: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False

- name: Install Docker
  package:
    name: docker.io
    state: latest
  become: true

- name: Add user student to docker group
  user:
    name: student
    groups: sudo,docker
  become: true
