---

- name: install some commonly used packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - htop
    - vim

- name: set the server motd
  copy: src=motd
        dest=/etc/motd
        mode=644

- name: disable ssh root logins without the use of a valid ssh key
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp='^PermitRootLogin ' line='PermitRootLogin without-password'
  notify: restart sshd
